version: '3.7'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 777
    ports:
      - 5432:5432
